# suppress inspection "UnusedProperty" for whole file
spring.cloud.gcp.datastore.emulator.enabled=true
spring.cloud.gcp.datastore.emulator.port=8090
spring.cloud.gcp.datastore.emulator.firestore-in-datastore-mode=true
spring.cloud.gcp.datastore.emulator.store-on-disk=false